insert into ESTADO (id_estado, nombre) values (1, 'Alabama');
insert into ESTADO (id_estado, nombre) values (2, 'Alaska');
insert into ESTADO (id_estado, nombre) values (3, 'Arizona');
insert into ESTADO (id_estado, nombre) values (4, 'Arkansas');
insert into ESTADO (id_estado, nombre) values (5, 'California');
insert into ESTADO (id_estado, nombre) values (6, 'Colorado');
insert into ESTADO (id_estado, nombre) values (7, 'Connecticut');
insert into ESTADO (id_estado, nombre) values (8, 'Delaware');
insert into ESTADO (id_estado, nombre) values (9, 'Florida');
insert into ESTADO (id_estado, nombre) values (10, 'Georgia');
insert into ESTADO (id_estado, nombre) values (11, 'Hawaii');
insert into ESTADO (id_estado, nombre) values (12, 'Idaho');
insert into ESTADO (id_estado, nombre) values (13, 'Illinois');
insert into ESTADO (id_estado, nombre) values (14, 'Indiana');
insert into ESTADO (id_estado, nombre) values (15, 'Iowa');
insert into ESTADO (id_estado, nombre) values (16, 'Kansas');
insert into ESTADO (id_estado, nombre) values (17, 'Kentucky');
insert into ESTADO (id_estado, nombre) values (18, 'Louisiana');
insert into ESTADO (id_estado, nombre) values (19, 'Maine');
insert into ESTADO (id_estado, nombre) values (20, 'Maryland');
insert into ESTADO (id_estado, nombre) values (21, 'Massachusetts');
insert into ESTADO (id_estado, nombre) values (22, 'Michigan');
insert into ESTADO (id_estado, nombre) values (23, 'Minnesota');
insert into ESTADO (id_estado, nombre) values (24, 'Mississippi');
insert into ESTADO (id_estado, nombre) values (25, 'Missouri');
insert into ESTADO (id_estado, nombre) values (26, 'Montana');
insert into ESTADO (id_estado, nombre) values (27, 'Nebraska');
insert into ESTADO (id_estado, nombre) values (28, 'Nevada');
insert into ESTADO (id_estado, nombre) values (29, 'New Hampshire');
insert into ESTADO (id_estado, nombre) values (30, 'New Jersey');
insert into ESTADO (id_estado, nombre) values (31, 'New Mexico');
insert into ESTADO (id_estado, nombre) values (32, 'New York');
insert into ESTADO (id_estado, nombre) values (33, 'North Carolina');
insert into ESTADO (id_estado, nombre) values (34, 'North Dakota');
insert into ESTADO (id_estado, nombre) values (35, 'Ohio');
insert into ESTADO (id_estado, nombre) values (36, 'Oklahoma');
insert into ESTADO (id_estado, nombre) values (37, 'Oregon');
insert into ESTADO (id_estado, nombre) values (38, 'Pennsylvania');
insert into ESTADO (id_estado, nombre) values (39, 'Rhode Island');
insert into ESTADO (id_estado, nombre) values (40, 'South Carolina');
insert into ESTADO (id_estado, nombre) values (41, 'South Dakota');
insert into ESTADO (id_estado, nombre) values (42, 'Tennessee');
insert into ESTADO (id_estado, nombre) values (43, 'Texas');
insert into ESTADO (id_estado, nombre) values (44, 'Utah');
insert into ESTADO (id_estado, nombre) values (45, 'Vermont');
insert into ESTADO (id_estado, nombre) values (46, 'Virginia');
insert into ESTADO (id_estado, nombre) values (47, 'Washington');
insert into ESTADO (id_estado, nombre) values (48, 'West Virginia');
insert into ESTADO (id_estado, nombre) values (49, 'Wisconsin');
insert into ESTADO (id_estado, nombre) values (50, 'Wyoming');
